### PR TITLE
Update for htslib version 1.9.

### PR DESCRIPTION
**Pull request by junaruga**
I came from https://bugzilla.redhat.com/show_bug.cgi?id=1326504 .
I updated htslib to latest version 1.9.

* Add necessary files to build by "fedpkg srpm".
* Add gcc, bzip2-devel and xz-devel as a build dependency.

Below is the result of mock build and koji's scratch build.

```
$ git branch
* feature/update-to-1.9
  master

$ fedpkg --release master srpm

$ mock -r fedora-rawhide-x86_64 *.src.rpm

$ koji build --scratch --nowait rawhide *.src.rpm
```

The scratch build (ok): https://koji.fedoraproject.org/koji/taskinfo?taskID=37504280

Below is the result of rpmlint.
`htslib.x86_64: W: shared-lib-calls-exit /usr/lib64/libhts.so.1.9 exit@GLIBC_2.2.5` can be cared.
But I think it's fine for this time. In the future, we can fix it with patching it.

```
$ rpmlint -i ./*.spec /var/lib/mock/fedora-rawhide-x86_64/result/*.rpm
htslib.src: W: spelling-error %description -l en_US samtools -> toadstools
The value of this tag appears to be misspelled. Please double-check.

htslib.src: W: spelling-error %description -l en_US bcftools -> footstools
The value of this tag appears to be misspelled. Please double-check.

htslib.x86_64: W: spelling-error %description -l en_US samtools -> toadstools
The value of this tag appears to be misspelled. Please double-check.

htslib.x86_64: W: spelling-error %description -l en_US bcftools -> footstools
The value of this tag appears to be misspelled. Please double-check.

htslib.x86_64: W: shared-lib-calls-exit /usr/lib64/libhts.so.1.9 exit@GLIBC_2.2.5
This library package calls exit() or _exit(), probably in a non-fork()
context. Doing so from a library is strongly discouraged - when a library
function calls exit(), it prevents the calling program from handling the
error, reporting it to the user, closing files properly, and cleaning up any
state that the program has. It is preferred for the library to return an
actual error code and let the calling program decide how to handle the
situation.

htslib-tools.x86_64: W: spelling-error %description -l en_US tbi -> ti, bi, bit
The value of this tag appears to be misspelled. Please double-check.

htslib-tools.x86_64: W: spelling-error %description -l en_US csi -> sci, cs, sic
The value of this tag appears to be misspelled. Please double-check.

7 packages and 1 specfiles checked; 0 errors, 7 warnings.
```

I could not understand below comment. If you think it is not necessary, I can remove the comments in this pull-request.

```
# Currently not providing explicit support for building with bzip2/lzma support
# as I am under the impression the implementation is a bit shaky from a comment
# in the source https://github.com/samtools/htslib/blob/develop/Makefile#L36-38
# Note that support for both are optional, not required for CRAM.
```

Because when upgrading htslib to 1.9 and building it, I needed `bzip2-devel` and `xz-devel` as a build dependency, as I faced below build errors.

```
cram/cram_io.c:57:10: fatal error: bzlib.h: No such file or directory
   57 | #include <bzlib.h>
      |          ^~~~~~~~~
compilation terminated.
```

```
cram/cram_io.c:61:10: fatal error: lzma.h: No such file or directory
   61 | #include <lzma.h>
      |          ^~~~~~~~
```

Could you review it?
Thank you.

### CODE REVIEW

**Comment by SamStudio8** [comment]
Thanks for fixing this! I never quite got my package to work. I think you can remove the bzip2/lzma comment now as that's an old implementation issue :)

**Comment by SamStudio8** [comment]
Thanks @junaruga!

**Comment by junaruga** [comment]
Hi @SamStudio8 . Sure, I removed the comment.
I also removed glibc-common and ncurses from build dependency, because I could build htslib without them.

I assigned `%license` tag to `LICENSE` rather than `%doc`.

```
-%doc LICENSE NEWS
+%license LICENSE
+%doc NEWS
```

Because in my understanding, `%license` tag started to use.

https://github.com/rpm-software-management/rpm/blob/master/CHANGES#L1832
> - add %license/%readme virtual file attributes.

https://src.fedoraproject.org/rpms/gcc/blob/master/f/gcc.spec#_2273
> %license gcc/COPYING* COPYING.RUNTIME

**Comment by junaruga** [comment]
Thanks for merging!

New koji scratch build: https://koji.fedoraproject.org/koji/taskinfo?taskID=37509125

**Comment by junaruga** [comment]
@SamStudio8 could you comment on below Bugzilla ticket to clarify remaining tasks? I can inherit the work from you if you are busy, but I need to know what are the tasks.
After we can start to manage the htslib RPM package on official fedora repository, maintaining it can be much easier.
https://bugzilla.redhat.com/show_bug.cgi?id=1326504

Thank you for your help.

**Comment by SamStudio8** [comment]
Hi @junaruga! I've never packaged anything for Fedora before, so this was my first attempt. I had some assistance back then but I didn't find the documentation on making packages very clear, which is why the version you fixed was failing `rpmlint`. If you know what you are doing then you are welcome to take this over!

**Comment by junaruga** [comment]
Sure, as I have experienced many RPM packaging on Fedora, I am familiar with RPM packaging proces specific things. I try to proceed it. :)
